[parameters]
alpha = [0.05, 0.075, 0.1, 0.15, 0.225,0.4]
beta1 = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
beta2 = [1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
r = [0.9, 0.85, 0.8, 0.75, 0.7, 0.3]
v0 = 1
M = 10000
omega = 0.1
p_min = 10
p_max = 50
