[parameters]
alpha = [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]
beta1 = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
beta2 = [1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
r = [0.1, 0.2, 0.4, 0.6, 0.8, 0.9]
v0 = 1
M = 10000
omega = 0.1
p_min = 10
p_max = 50
